services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d testdb -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/testdb
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  db_data:
